export default {
    name: "Nastaran Jalali",
    home: "HOME",
    about: "ABOUT",
    resume: "RESUME",
    portfolios: "PORTFOLIOS",
    contact: "CONTACT",
    hi1: "Hi, I am ",
    hi2: "",
    homeDesc: "I am a frontend web developer who is bluh bluh bluh I just want it to be long enough to take multiple lines in both languages ",
    aboutMe: "ABOUT ME",
    fullName: "Full Name",
    age: "Age",
    nationality: "Nationality",
    languages: "Languages",
    phone: "Phone",
    years: "years",
    iranian: "Iranian",
    persian: "Persian",
    english: "English",
    german: "German",
    services: "Services",
    downloadcv: "download CV",
    webDesign: "Web Design",
    webDevelopment: "Web Development",
    mobileApplication: "Mobile Application",
    designDesc: "Implementing user interfaces with React, React Router, and Material UI, CSS, JSS, and Bootstrap for styling. Creating responsive websites",
    developDesc: "there's nothing special right now but I promise you there will be :') probably GO or something",
    mobileAppDesc: "there's nothing special right now but I promise you there will be :') I mean it has to be 3 services I'm not very interested in mobile apps though",
    mySkills: "My Skills",
    html5 : "HTML5",
    css3: "CSS3",
    js:"JavaScript",
    jquery:"JQuery",
    reactJS:"React js",
    bootstrap:"Bootstrap",
    materialUI:"MaterialUI",
    photoshop:"PhotoShop",

}