export default {
    name: "Nastaran Jalali",
    home: "HOME",
    about: "ABOUT",
    resume: "RESUME",
    portfolios: "PORTFOLIO",
    contact: "CONTACT",
    hi1: "Hi, I am ",
    hi2: "",
    homeDesc: "I am a frontend web developer who is bluh bluh bluh I just want it to be long enough to take multiple lines in both languages ",
    aboutMe: "ABOUT ME",
    fullName: "Full Name",
    age: "Age",
    nationality: "Nationality",
    languages: "Languages",
    phone: "Phone",
    years: "years",
    iranian: "Iranian",
    persian: "Persian",
    english: "English",
    german: "German",
    services: "Services",
    downloadcv: "download CV",
    webDesign: "Web Design",
    webDevelopment: "Web Development",
    mobileApplication: "Mobile Application",
    designDesc: "Implementing user interfaces with React, React Router, and Material UI, CSS, JSS, and Bootstrap for styling. Creating responsive websites",
    developDesc: "there's nothing special right now but I promise you there will be :') probably GO or something",
    mobileAppDesc: "there's nothing special right now but I promise you there will be :') I mean it has to be 3 services I'm not very interested in mobile apps though",
    mySkills: "My Skills",
    html5 : "HTML5",
    css3: "CSS3",
    js:"JavaScript",
    jquery:"JQuery",
    reactJS:"React js",
    bootstrap:"Bootstrap",
    materialUI:"MaterialUI",
    photoshop:"PhotoShop",
    workExperience :"Work Experience",
    boardgamePresenter:"Board Game Presenter",
    frontendDeveloper :"Frontend Developer",
    jobFirstYear:"2020 - 2021",
    jobFirstTitle:"Board Game Presenter",
    jobFirstCompany:"Bordar Group",
    jobFirstDesc:"Game presenter in bordar group, I have mastered a lot of board games and I can win all of you ",
    jobSecondYear:"2021 - now",
    jobSecondTitle:"Frontend Developer",
    jobSecondCompany:"Adl Afarinan Mandegar co.",
    jobSecondDesc:"Frontend developer at Adl Afarinan Mandegar, I'm still learning so I don't know what to say in this section bluh bluh bluh as usual",
    educationalQualification:"Educational Qualification",
    firstDegreeYear:"2012 - 2018",
    firstDegree:"High School Diploma (Theoretical and Mathematical Physics)",
    firstSchoolName:"National Organization for Development of Exceptional Talents (Sampad)",
    firstLocation:"Iran , Saveh",
    secondDegreeYear:"2019 - 2023",
    secondDegree:"Bachelor's degree (Computer Engineering)",
    secondSchoolName:"Kharazmi University",
    secondLocation:"Iran , Karaj",
    contactMe:"Contact Me",
    getInTouch:"Get In Touch",
    enterYourName:'Enter your name',
    enterYourEmail:"Enter your Email",
    enterYourSubject:"Enter your subject",
    enterYourMessage:"Enter your message",
    email:"Email",
    address:"Address",
    send:"Send Massage",
    emailAddress:"nastaranjalalibusiness@gmail.com",
    addressDesc:"Iran, Tehran",





}